project_id_env: 'CROWDIN_PROJECT_ID'
api_token_env: 'CROWDIN_API_TOKEN'
base_path: '.'

commit_message: '[Crowdin] Update source files (%original_file_name%)'
preserve_hierarchy: true

files:
  - source: '/common/src/main/resources/assets/*/lang/en_us.json'
    translation: '/common/src/main/resources/assets/*/lang/%locale%.json'
    languages_mapping:
      locale:
        af: af
        ar: ar
        ca: ca
        zh-CN: zh_CN
        zh-TW: zh_TW
        cs: cs
        da: da
        nl: nl
        en-US: en_US
        en-AU: en_AU
        en-GB: en_GB
        fi: fi
        fr: fr
        de: de
        el: el
        he: he
        hu: hu
        it: it
        ja: ja
        ko: ko
        nb: nb
        pl: pl
        pt: pt
        pt-BR: pt_BR
        ro: ro
        ru: ru
        sr: sr
        es: es
        es-MX: es_MX
        sv: sv
        tr: tr
        uk: uk
        vi: vi
