modLoader = "javafml"
loaderVersion = "[4,)"
license = "Apache-2.0"

[[mods]]
modId = "cmd_delete"
version = "${version}"
displayName = "CMD + Delete"
description = "Fix macOS text navigation shortcuts in chat/books/signs/etc + allow custom shortcuts."
displayURL = "https://omegabird113.github.io/CMD_Delete/"
issueTrackerURL = "https://github.com/Omegabird113/CMD_Delete/issues"
iconFile = "assets/cmd_delete/icon.png"
authors = "Omegabird113"

[[mixins]]
config = "cmd_delete.mixins.json"

[[dependencies.cmd_delete]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_min_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.cmd_delete]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,26.3)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.cmd_delete]]
modId = "macos-chat-fixes"
type = "incompatible"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"