/*
 * Copyright (c) 2026 Omegabird113.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'net.neoforged.moddev' version '2.0.144'
    id 'maven-publish'
}

base {
    archivesName = project.archives_base_name + "-neoforge"
}

configurations {
    shadeOnly
}

sourceSets {
    main {
        compileClasspath += configurations.shadeOnly
        runtimeClasspath += configurations.shadeOnly
    }
    test {
        compileClasspath += configurations.shadeOnly
        runtimeClasspath += configurations.shadeOnly
    }
}

dependencies {
    implementation project(":common")

    shadeOnly 'com.google.code.gson:gson:2.14.0'
    shadeOnly 'org.jspecify:jspecify:1.0.1'
    shadeOnly 'commons-codec:commons-codec:1.22.1'
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            systemProperty 'cmd_delete.ci.stopMinecraftAfterLoad', System.getProperty('cmd_delete.ci.stopMinecraftAfterLoad', 'false')
        }
    }

    mods {
        cmd_delete {
            sourceSet sourceSets.main
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

processResources {
    from(project(":common").sourceSets.main.resources)
    inputs.property "version", project.version
    inputs.property "neoforge_min_version", project.neoforge_min_version
    filteringCharset "UTF-8"

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version,
                "neoforge_min_version": project.neoforge_min_version
    }
}

tasks.jar {
    from("${rootDir}/LICENSE") {
        rename { "LICENSE.txt" }
    }
    from("${rootDir}/NOTICE") {
        rename { "NOTICE.txt" }
    }
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.maven_group
            artifactId = project.archives_base_name + "-neoforge"
            version = project.version
            from components.java
        }
    }

    repositories {
        maven {
            url "file://${System.getenv('MAVEN_PASS_DIR')}"
        }
    }
}
